default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: ruby_and_react_development


test:
  <<: *default
  database: ruby_and_react_development
